name: JavaScript CI with Selenium and baked-in vanilla e2e
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.selenium.conclusion }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install geckodriver
        uses: browser-actions/setup-geckodriver@latest
      - run: geckodriver --version
      - name: install firefox
        uses: browser-actions/setup-firefox@latest
      - run: firefox --version
      #- run: |
       #   npm ci
       #   npm start & npx wait-on http://localhost:3000
      #- name: Run Selenium test
      #  id: selenium
      #  uses: ./
  #push:
   # needs: test
    #runs-on: ubuntu-latest
    #if: needs.test.outputs.status == 'success'
    #steps:
    #  - uses: actions/checkout@v2
    #  - name: Commit report
    #    run: |
     #     git config --global user.name '$github.actor'
      #    git config --global user.email '$github.actor@users.noreply.github.com'
      #    git commit -am '${{ github.event.head_commit.message }}'
      #    git push